import React from 'react';


const TableContent = () => {
    return (
        <table id="example" class="display nowrap" width="100%">
            <thead>
              <tr>
                <th>Subject</th>
                <th>Age</th>
                <th>Sex</th>
                <th>OnsetAge</th>
                <th>Handedness</th>
                <th>DomHemi</th>
                <th>Wada</th>
                <th>fMRI</th>
                <th>CSM</th>
                <th>SurgHemi</th>
                <th>SurgType</th>
                <th>SurgDescription</th>
                <th>SurgDate</th>
                <th>ILAE</th>
                <th>Engel</th>
                <th>Etiology</th>
                <th>MRI</th>
                <th>SurgHx</th>
                <th>SurgHxHemi</th>
                <th>SurgHxType</th>
                <th>SurgHxDate</th>
                <th>PreNP_DOE</th>
                <th>PostNP_DOE</th>
                <th>FSIQ</th>
                <th>English</th>
                <th>VNS</th>
                <th>ECoG_Hemi</th>
                <th>ECoG</th>
                <th>ImplantDate</th>
                <th>ExplantDate</th>
                <th>AwakeCSM</th>
                <th>AwakeCSM_Tasks</th>
                <th>AsleepCSM</th>
                <th>AsleepCSM_Tasks</th>
                <th>Prime</th>
                <th>ThalamusStim</th>
                <th>Meg</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th>TA310</th>
                <th>50</th>
                <th>F</th>
                <th>26</th>
                <th>R</th>
                <th>B</th>
                <th>-</th>
                <th>B</th>
                <th> </th>
                <th>R</th>
                <th>ATL+AH</th>
                <th>ATL+AH</th>
                <th>6/19/07</th>
                <th>1</th>
                <th>1a</th>
                <th>MTS</th>
                <th>MTS (R)</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th></th>
                <th>2/20/08</th>
                <th>96</th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>Y</th>
                <th></th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th>
              </tr>
              <tr>
                <th>TA311</th>
                <th>62</th>
                <th>F</th>
                <th>25</th>
                <th>R</th>
                <th>L</th>
                <th>-</th>
                <th>L</th>
                <th> </th>
                <th>L</th>
                <th>ATL+AH+Other</th>
                <th>ATL+AH+TP</th>
                <th>6/29/07</th>
                <th>3</th>
                <th>1c</th>
                <th>MTS</th>
                <th>MTS (L)</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th>4/10/07</th>
                <th>11/20/07</th>
                <th>107</th>
                <th></th>
                <th></th>
                <th>L</th>
                <th>SDE</th>
                <th></th>
                <th></th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th>
              </tr>
              <tr>
                <th>TA312</th>
                <th>43</th>
                <th>F</th>
                <th>17</th>
                <th>R</th>
                <th>R</th>
                <th>R</th>
                <th>R</th>
                <th> </th>
                <th>L</th>
                <th>ATL+AH</th>
                <th>ATL+AH</th>
                <th>2/22/05</th>
                <th>1</th>
                <th>1a</th>
                <th>febrile seizure; MTS</th>
                <th>MTS (L)</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th>9/10/04</th>
                <th>-</th>
                <th>89</th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th>
              </tr>
              <tr>
                <th>TA313</th>
                <th>44</th>
                <th>F</th>
                <th> </th>
                <th>R</th>
                <th>L</th>
                <th>-</th>
                <th>L</th>
                <th> </th>
                <th>L</th>
                <th>Other</th>
                <th>FOP</th>
                <th>6/26/07</th>
                <th></th>
                <th></th>
                <th>astrocytoma</th>
                <th>tumor</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>Spanish</th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>Y</th>
                <th>language; motor</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th>
              </tr>
              <tr>
                <th>TA314</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th>
              </tr>
              <tr>
                <th>TA315</th>
                <th>31</th>
                <th>F</th>
                <th>21</th>
                <th>R</th>
                <th>L</th>
                <th>L</th>
                <th>B</th>
                <th> </th>
                <th>R</th>
                <th>Other</th>
                <th>OFC</th>
                <th>7/18/07</th>
                <th>1</th>
                <th>1a</th>
                <th>TBI</th>
                <th>encephalomalacia</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th></th>
                <th></th>
                <th>78</th>
                <th></th>
                <th></th>
                <th>R</th>
                <th>SDE</th>
                <th></th>
                <th></th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th>
              </tr>
              <tr>
                <th>TA316</th>
                <th>42</th>
                <th>F</th>
                <th>41</th>
                <th>R</th>
                <th>L</th>
                <th>-</th>
                <th>L</th>
                <th> </th>
                <th>L</th>
                <th>Other</th>
                <th>Wernicke</th>
                <th>7/25/07</th>
                <th>1</th>
                <th>1a</th>
                <th>cav mal</th>
                <th>cav mal</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th></th>
                <th></th>
                <th>99</th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>Y</th>
                <th>language</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th>
              </tr>
              <tr>
                <th>TA317</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th>
              </tr>
              <tr>
                <th>TA318</th>
                <th>52</th>
                <th>M</th>
                <th> </th>
                <th>R</th>
                <th>L</th>
                <th>-</th>
                <th>L</th>
                <th></th>
                <th>L</th>
                <th>Other</th>
                <th>P</th>
                <th>10/15/07</th>
                <th></th>
                <th></th>
                <th>glioma</th>
                <th>tumor</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>Y</th>
                <th>language; motor</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th>
              </tr>
              <tr>
                <th>TA319</th>
                <th>38</th>
                <th>F</th>
                <th>37</th>
                <th>R</th>
                <th>L</th>
                <th>-</th>
                <th>L</th>
                <th></th>
                <th>R</th>
                <th>Other</th>
                <th>STG</th>
                <th>11/14/07</th>
                <th>2</th>
                <th>1b</th>
                <th>cav mal</th>
                <th>cav mal</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th>
              </tr>
              <tr>
                <th>TA319B</th>
                <th>40</th>
                <th>F</th>
                <th>37</th>
                <th>R</th>
                <th>L</th>
                <th>-</th>
                <th>L</th>
                <th></th>
                <th>L</th>
                <th>Other</th>
                <th>F</th>
                <th>1/14/09</th>
                <th>2</th>
                <th>1b</th>
                <th>cav mal</th>
                <th>cav mal</th>
                <th>Y</th>
                <th>R</th>
                <th>STG</th>
                <th>11/14/07</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>Y</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th>
              </tr>
              <tr>
                <th>TA320</th>
                <th>35</th>
                <th>M</th>
                <th>14</th>
                <th>L</th>
                <th>R</th>
                <th>R</th>
                <th>R</th>
                <th></th>
                <th>L</th>
                <th>ATL+AH</th>
                <th>ATL+AH</th>
                <th>12/18/07</th>
                <th>5</th>
                <th>4b</th>
                <th>meningitis</th>
                <th>MTS (L)</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th>8/21/07</th>
                <th>3/11/08</th>
                <th>101</th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th>
              </tr>
              <tr>
                <th>TA320B</th>
                <th>35</th>
                <th>M</th>
                <th>14</th>
                <th>L</th>
                <th>R</th>
                <th>R</th>
                <th>R</th>
                <th></th>
                <th>L</th>
                <th>Other</th>
                <th>TO</th>
                <th>6/6/08</th>
                <th>5</th>
                <th>4b</th>
                <th>meningitis</th>
                <th>MTS (L)</th>
                <th>Y</th>
                <th>L</th>
                <th>ATL+AH</th>
                <th>12/18/07</th>
                <th>8/21/07</th>
                <th></th>
                <th>101</th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th> 
              </tr>
              <tr>
                <th>TA321</th>
                <th>40</th>
                <th>F</th>
                <th>39</th>
                <th>L</th>
                <th></th>
                <th>-</th>
                <th>I</th>
                <th>L?</th>
                <th>L</th>
                <th>Other</th>
                <th>Insula</th>
                <th>11/28/07</th>
                <th>1</th>
                <th>1a</th>
                <th>cyst</th>
                <th>cyst</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>Y</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th> 
              </tr>
              <tr>
                <th>TA322</th>
                <th>34</th>
                <th>F</th>
                <th>0.75</th>
                <th>R</th>
                <th>L</th>
                <th>L</th>
                <th>L</th>
                <th></th>
                <th>L</th>
                <th>ATL+AH</th>
                <th>ATL+AH</th>
                <th>12/18/07</th>
                <th>1</th>
                <th>1a</th>
                <th>febrile seizure; MTS</th>
                <th>MTS (L)</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th>3/13/07</th>
                <th>5/28/08</th>
                <th>101</th>
                <th></th>
                <th></th>
                <th></th>
                <th>SDE</th>
                <th></th>
                <th></th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th> 
              </tr>
              <tr>
                <th>TA323</th>
                <th>28</th>
                <th>M</th>
                <th>6</th>
                <th>R</th>
                <th>L</th>
                <th>L</th>
                <th>L</th>
                <th></th>
                <th>R</th>  
                <th>Other</th>
                <th>TPJ</th>
                <th>12/24/07</th>
                <th>4</th>
                <th>3a</th>
                <th>TBI (Blunt); FCD1</th>
                <th>normal</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th></th>
                <th></th>
                <th>94</th>
                <th></th>
                <th></th>
                <th>B</th>
                <th>SDE</th>
                <th></th>
                <th></th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>Y</th> 
              </tr>
              <tr>
                <th>TA324</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th>
              </tr>
              <tr>
                <th>TA325</th>
                <th>30</th>
                <th>M</th>
                <th>1</th>
                <th>R</th>
                <th>L</th>
                <th>L</th>
                <th>L</th>
                <th></th>
                <th>R</th>  
                <th>ATL+AH</th>
                <th>ATL+AH</th>
                <th>1/16/08</th>
                <th>3</th>
                <th>1c</th>
                <th>MTS</th>
                <th>MTS (R)</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th></th>
                <th>7/9/08</th>
                <th>98</th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th> 
              </tr>
              <tr>
                <th>TA326</th>
                <th>20</th>
                <th>M</th>
                <th>8</th>
                <th>R</th>
                <th>L</th>
                <th>L</th>
                <th>L</th>
                <th></th>
                <th>R</th>  
                <th>ATL</th>
                <th>ATL</th>
                <th>2/13/08</th>
                <th>1</th>
                <th>1a</th>
                <th>cyst</th>
                <th>cyst (RT)</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th></th>
                <th>11/10/08</th>
                <th>99</th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th> 
              </tr>
              <tr>
                <th>TA327</th>
                <th>43</th>
                <th>M</th>
                <th>10</th>
                <th>L</th>
                <th>R</th>
                <th>R</th>
                <th>R</th>
                <th></th>
                <th>R</th>  
                <th>ATL+AH</th>
                <th>ATL+AH</th>
                <th>3/6/08</th>
                <th>1</th>
                <th>1a</th>
                <th>MTS</th>
                <th>MTS (R)</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th>1/30/08</th>
                <th>11/19/08</th>
                <th>-</th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>Y</th>
                <th>language</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th> 
              </tr>
              <tr>
                <th>TA328</th>
                <th>27</th>
                <th>M</th>
                <th>11</th>
                <th>R</th>
                <th>L</th>
                <th>L</th>
                <th>B</th>
                <th></th>
                <th>L</th>  
                <th>Other</th>
                <th>PO</th>
                <th>4/23/08</th>
                <th>-</th>
                <th>-</th>
                <th>ganglioglioma</th>
                <th>tumor</th>
                <th>Y</th>
                <th>L</th>
                <th>gangliocytoma</th>
                <th>6/25/05</th>
                <th></th>
                <th></th>
                <th>92</th>
                <th>Spanish</th>
                <th>N</th>
                <th>L</th>
                <th>SDE</th>
                <th>-</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th> 
              </tr>
              <tr>
                <th>TA328</th>
                <th>27</th>
                <th>M</th>
                <th>11</th>
                <th>R</th>
                <th>L</th>
                <th>L</th>
                <th>B</th>
                <th></th>
                <th>L</th>  
                <th>Other</th>
                <th>PO</th>
                <th>4/23/08</th>
                <th>-</th>
                <th>-</th>
                <th>ganglioglioma</th>
                <th>tumor</th>
                <th>Y</th>
                <th>L</th>
                <th>gangliocytoma</th>
                <th>6/25/05</th>
                <th></th>
                <th></th>
                <th>92</th>
                <th>Spanish</th>
                <th>N</th>
                <th>L</th>
                <th>SDE</th>
                <th>-</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th> 
              </tr>
              <tr>
                <th>TA329</th>
                <th>55</th>
                <th>M</th>
                <th>35</th>
                <th>R</th>
                <th>L</th>
                <th>L</th>
                <th>B</th>
                <th></th>
                <th>L</th>  
                <th>ATL</th>
                <th>ATL</th>
                <th>4/16/08</th>
                <th>1</th>
                <th>1a</th>
                <th>encephalocele</th>
                <th>encephalocele</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th></th>
                <th>11/5/08</th>
                <th>106</th>
                <th></th>
                <th></th>
                <th>-</th>
                <th>NONE</th>
                <th>-</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th> 
              </tr>
              <tr>
                <th>TA330</th>
                <th>61</th>
                <th>M</th>
                <th>29</th>
                <th>R</th>
                <th>L</th>
                <th>-</th>
                <th>L</th>
                <th></th>
                <th>L</th>  
                <th>Other</th>
                <th>TO</th>
                <th>8/13/08</th>
                <th>4</th>
                <th>3a</th>
                <th>TBI (MVA)</th>
                <th>normal</th>
                <th>N</th>
                <th>-</th>
                <th>-</th>
                <th>-</th>
                <th>2/25/08</th>
                <th>1/21/09</th>
                <th>104</th>
                <th></th>
                <th></th>
                <th>L</th>
                <th>SDE</th>
                <th>-</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>-</th>
                <th>N</th>
                <th>N</th>
                <th>N</th> 
              </tr>
              
            </tbody>
      </table>
    );
};

export default TableContent;